<form class="m-5 d-flex flex-wrap flex-row align-items-center" method="POST" action="Data/PushPrelevement">

  <div class="mb-3 w-25 w-25">
    <label for="Sample" class="form-label">Echantillon</label>
    <input type="text" class="form-control w-75" id="Sample" aria-describedby="Input Sample" name="sample">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="Sea" class="form-label">Mer</label>
    <select name="sea" id="select-seas" class="select-seas form-control w-75">
      <?php foreach ($seas as $sea) : ?>
        <option value="<?= $sea['name'] ?>"><?= $sea['name'] ?></option>
      <?php endforeach; ?>
    </select>

  </div>
  <div class="mb-3 w-25 w-25">
    <label for="Date" class="form-label">Date</label>
    <input type="text" class="form-control w-75" id="Date" name="date" placeholder="dd/mm/yy">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="StartTime" class="form-label">Date de début</label>
    <input type="text" class="form-control w-75" id="StartTime" name="startTime" placeholder="ex:10h00">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="StartLatitude" class="form-label">Début latitude</label>
    <input type="text" class="form-control w-75" id="StartLatitude" name="startLatitude" placeholder="42°07.843 N">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="StartLongitude" class="form-label">Début longitude</label>
    <input type="text" class="form-control w-75" id="StartLongitude" name="startLongitude" placeholder="42°07.843 N">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="MidLatitude" class="form-label">Milieu Latitude</label>
    <input type="text" class="form-control w-75" id="MidLatitude" name="midLatitude" placeholder="42°07.843 N">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="MidLongitude" class="form-label">Millieu Longitude</label>
    <input type="text" class="form-control w-75" id="MidLongitude" name="midLongitude" placeholder="42°07.843 N">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="EndLatitude" class="form-label">Fin Latitude</label>
    <input type="text" class="form-control w-75" id="EndLatitude" name="endLatitude" placeholder="42°07.843 N">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="EndLongitude" class="form-label">Fin Longitude</label>
    <input type="text" class="form-control w-75" id="EndLongitude" name="endLongitude" placeholder="42°07.843 N">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="WindForce" class="form-label">Force du Vent</label>
    <input type="text" class="form-control w-75" id="WindForce" name="windForce" placeholder="exemple:10">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="WindSpeed" class="form-label">Vitesse du Vent</label>
    <input type="text" class="form-control w-75" id="WindSpeed" name="windSpeed" placeholder="exemple:1">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="WindDirection" class="form-label">Direction du Vent</label>
    <input type="text" class="form-control w-75" id="WindDirection" name="windDirection" placeholder="exemple:255">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="SeaState" class="form-label">Etat de la Mer</label>
    <input type="text" class="form-control w-75" id="SeaState" name="seaState" placeholder="exemple:1">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="WaterTemperature" class="form-label">Température de l'Eau</label>
    <input type="text" class="form-control w-75" id="WaterTemperature" name="waterTemperature" placeholder="exemple:27.3">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="BoatSpeed" class="form-label">Vitesse du Bateau</label>
    <input type="text" class="form-control w-75" id="BoatSpeed" name="boatSpeed" placeholder="exemple:2.2">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="StartFlowMeter" class="form-label">Début hauteur d'eau</label>
    <input type="text" class="form-control w-75" id="StartFlowMeter" name="startFlowMeter" placeholder="exemple:53225">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="EndFlowMeter" class="form-label">Fin hauteur d'eau</label>
    <input type="text" class="form-control w-75" id="EndFlowMeter" name="endFlowMeter" placeholder="exemple:61255">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="FilteredVolume" class="form-label">Volume filtré</label>
    <input type="text" class="form-control w-75" id="FilteredVolume" name="filteredVolume" placeholder="exemple:290">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="FilteredDistance" class="form-label">Distance filtrée</label>
    <input type="text" class="form-control w-75" id="FilteredDistance" name="filteredDistance" placeholder="exemple:2037">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="FilteredSurface" class="form-label">Surface filtrée (m)</label>
    <input type="text" class="form-control w-75" id="FilteredSurface" name="filteredSurface" placeholder="exemple:1227">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="FilteredSurfaceKm" class="form-label">Surface filtrée (KM)</label>
    <input type="text" class="form-control w-75" id="FilteredSurfaceKm" name="filteredSurfaceKm" placeholder="exemple:0.001">
  </div>
  <div class="mb-3 w-25 w-25">
    <label for="ParticlesNumber" class="form-label">Nombre de particules</label>
    <input type="text" class="form-control w-75" id="ParticlesNumber" name="particlesNumber" placeholder="exemple:120">
  </div>
  <div class="mb-3 w-25 w-25 w-100">
    <label for="Commentaires" class="form-label">Commentaires</label>
    <textarea id="Commentaires" class="form-control" id="exampleFormControlTextarea1" rows="3" name="commentaires"></textarea>
  </div>


  <div class="w-100 text-center p-5"><button type="submit" class="btn btn-primary ">Soumettre</button></div>
</form>